apiVersion: batch/v1
kind: Job
metadata:
  name: 20230105004750-capit-v2-debug-regular-string-0
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - command:
        - /opt/conda/envs/main/bin/accelerate-launch
        - --mixed_precision=bf16
        - /app/capit/run.py
        - exp_name=capit-v2-debug
        - dataset.max_num_query_images_per_episode=50
        env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              key: WANDB_API_KEY
              name: capit-v2-debug
        - name: HF_TOKEN
          value: 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
        - name: HF_USERNAME
          value: evolvingfungus
        - name: WANDB_ENTITY
          value: machinelearningbrewery
        - name: WANDB_PROJECT
          value: capit-v2-debug
        - name: EXPERIMENTS_DIR
          value: /run/experiments
        - name: EXPERIMENT_DIR
          value: /run/experiments
        - name: DATASET_DIR
          value: /data/
        - name: MODEL_DIR
          value: /run/models
        - name: PROJECT_DIR
          value: null
        image: ghcr.io/bayeswatch/minimal-ml-template:latest
        imagePullPolicy: Always
        name: job-container
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /volume/dataset
          name: pvc-instagram-vol
        - mountPath: /data/
          name: pvc-instait-vol
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 80Gi
        name: dshm
      - name: pvc-instagram-vol
        persistentVolumeClaim:
          claimName: pvc-instagram-disk
      - name: pvc-instait-vol
        persistentVolumeClaim:
          claimName: pvc-instait
