apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-instait3
spec:
  storageClassName: pv-datasets3
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: pvc-instait3
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/tali-multi-modal/zones/us-central1-a/disks/instait-ssd
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc-instait3
spec:
  storageClassName: pv-datasets3
  volumeName: pv-instait3
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1500Gi